### ISSUE TITLE
no matches found: build/**/compile_commands.json

### ISSUE THREAD

**Issue by gokulmaxi** [zoenglinghou/catkin-compile-commands#1]
When i try to use this script,I get this error 
> no matches found: build/**/compile_commands.json

**Comment by gokulmaxi** [comment]
The error got cleared after using
$ catkin build -c -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=YES "$@"

**Comment by zoenglinghou** [comment]
Thank you for pointing that out.
You could also use
```cmake
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
```
in your `CMakeLists.txt`.

I have updated the README accordingly.
